name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.
        
        **Merci de signaler ce bug !** Vous pouvez remplir ce formulaire en français si vous préférez.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I am using the latest version of DevSpaces
          required: true

  - type: input
    id: version
    attributes:
      label: DevSpaces Version
      description: Run `dvs version` to get this
      placeholder: "0.2.15"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (Ubuntu/Debian)
        - Linux (Other)
        - Windows (WSL2)
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Container Runtime
      options:
        - Docker Desktop
        - OrbStack
        - Podman
        - Colima
        - Other
    validations:
      required: true

  - type: input
    id: recipe
    attributes:
      label: Recipe (if applicable)
      description: Which recipe are you using?
      placeholder: "wordpress, prestashop, laravel, custom..."

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Run `dvs ...`
        2. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Paste relevant logs here. You can get logs with:
        - `dvs logs` for container logs
        - `dvs debug` for diagnostic information
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem (screenshots, configuration, etc.)
